<?php

//官方彩
		$apiurls = [
			'actkeno'  => '/api.open.kj.code.actkeno',
			'bjkeno'   => 'http://api1.pm8888.cn/api.php?type=bjkeno',
			'jndkeno'  => '/api.open.kj.code.jndkeno',
			'hgkeno'   => '/api.open.kj.code.hgkeno',
			'twkeno'   => '/api.open.kj.code.twkeno',
			'cqssc'    => 'http://f.apiplus.net/cqssc.json',
			'xjssc'    => 'http://f.apiplus.net/xjssc.json',
			'tjssc'    => 'http://f.apiplus.net/tjssc.json',
			'dfssc'    => '/api.open.kj.code.dfssc',
			'df11x5'    => '/api.open.kj.code.df11x5',
			//--------------------------K3---------------------------------
			'nmgk3'    => 'http://f.apiplus.net/nmgk3.json',
			'hebk3'    => 'http://f.apiplus.net/hebk3.json',
			'bjk3'     => 'http://f.apiplus.net/fjk3.json',
			'shk3'     => 'http://f.apiplus.net/shk3.json',
			'jsk3'     => 'http://f.apiplus.net/jsk3.json',
			'jlk3'     => 'http://f.apiplus.net/jlk3.json',
			'ahk3'     => 'http://f.apiplus.net/ahk3.json',
			'gxk3'     => 'http://f.apiplus.net/gxk3.json',
			'gsk3'     => 'http://f.apiplus.net/gsk3.json',
			'hubk3'    => 'http://f.apiplus.net/hubk3.json',
			'jxk3'     => 'http://f.apiplus.net/jxk3.json',
			'fjk3'		=> 'http://f.apiplus.net/fjk3.json',
			'nmgk3'		=> 'http://f.apiplus.net/nmgk3.json',
			'gzk3'		=> 'http://f.apiplus.net/gzk3.json',
			'jsk3'		=> 'http://f.apiplus.net/jsk3.json',
			'qhk3'		=> 'http://f.apiplus.net/qhk3.json',
			'henk3'		=> 'http://f.apiplus.net/henk3.json',
			//-----------------------------11X5---------------------
			'gd11x5'    => 'http://f.apiplus.net/gd11x5.json',
			'jx11x5'    => 'http://f.apiplus.net/jx11x5.json',
			'sh11x5'    => 'http://f.apiplus.net/sh11x5.json',
			'tj11x5'	=> 'http://f.apiplus.net/tj11x5.json',
			'zj11x5'	=> 'http://f.apiplus.net/zj11x5.json',
			'bj11x5'	=> 'http://f.apiplus.net/bj11x5.json',
			'yn11x5'	=> 'http://f.apiplus.net/yn11x5.json',
			'nmg11x5'	=> 'http://f.apiplus.net/nmg11x5.json',
			'gx11x5'	=> 'http://f.apiplus.net/gx11x5.json',
			'qh11x5'	=> 'http://f.apiplus.net/qh11x5.json',
			'shx11x5'	=> 'http://f.apiplus.net/shx11x5.json',
			'hen11x5'	=> 'http://f.apiplus.net/hen11x5.json',
			'gs11x5'	=> 'http://f.apiplus.net/gs11x5.json',
			'heb11x5'	=> 'http://f.apiplus.net/heb11x5.json',
			'hlj11x5'	=> 'http://f.apiplus.net/hl11x5.json',
			'sd11x5'	=> 'http://f.apiplus.net/sd11x5.json',
			'xj11x5'	=> 'http://f.apiplus.net/xj11x5.json',
			'js11x5'	=> 'http://f.apiplus.net/js11x5.json',
			'fj11x5'	=> 'http://f.apiplus.net/fj11x5.json',
			'ah11x5'	=> 'http://f.apiplus.net/ah11x5.json',
			'hub11x5'	=> 'http://f.apiplus.net/hub11x5.json',
			'jl11x5'	=> 'http://f.apiplus.net/jl11x5.json',
			'sx11x5'	=> 'http://f.apiplus.net/sx11x5.json',
			'ln11x5'	=> 'http://f.apiplus.net/ln11x5.json',
			//-----------------------------X5  END-----------------------
			'gdkl10f'    => 'http://f.apiplus.net/gdklsf.json',
			'tjkl10f'    => 'http://f.apiplus.net/tjklsf.json',
			'cqkl10f'    => 'http://f.apiplus.net/cqklsf.json',
			'bjpk10'     => 'http://f.apiplus.net/bjpk10.json',   //北京pk10
			'txssc'     => 'http://xxx.com',
			'lhc'     => 'http://xxx.com',
			'fc3d'      => 'http://f.apiplus.net/fc3d.json',
			'pl3'       => 'http://f.apiplus.net/pl3.json',
			'xyft'       => 'http://106.12.156.111/api?token=f35e8b4035c098a2&code=mlaft&rows=1&format=json',   
			'ynwfc'    => '/api.open.kj.code.ynwfc',
			'ynffc'    => '/api.open.kj.code.ynffc',
			'hnwfc'    => '/api.open.kj.code.hnwfc',
			'hnffc'    => '/api.open.kj.code.hnffc',

		];
